### ISSUE TITLE
Update deps and expo

### ISSUE THREAD

**Issue by PatheticMustan** [PatheticMustan/ScoutingApp2020#1]
Okay, @00100000spacebar. Here's a super ezpz issue. ***In a pull request***, update the dependencies, and upgrade expo to sdk 39.

***Don't ask Yach and I for help. Learn to find and read documentation.***

ezpz

**Comment by PatheticMustan** [comment]
Please do this ;(

**Comment by PatheticMustan** [comment]
Finish upgrading expo or perish

**Comment by PatheticMustan** [comment]
lazy

**Comment by 00100000** [comment]
done pooping
