### ISSUE TITLE
add component state cache to all input components

### ISSUE THREAD

**Issue by PatheticMustan** [PatheticMustan/ScoutingApp2020#12]
Context: PatheticMustan/ScoutingApp2019#36

Unfortunately, Redux isn't instant. Normally this wouldn't be a problem, but since we use Redux to keep track of our input stuff, it becomes very noticable.

Redux updates its state through `actions`. It tells the store "Hey, the user just typed, here's the updated text", and the store passes it to a bunch of its workers, called `reducers`. Each reducer looks at the action.
"Sorry, I only look at NumButtons".
"Sorry, I only look at BoolButtons"
"Oh! I work with Textboxes! Let me do stuff!"

It makes state management much clearer, but it's not fast enough for textboxes. If we rely totally on Redux, it would rubber band back and forth, lose input, and whatever. It'd be painful.

This is why we use the component's state instead. It's faster, and instant.

Using both the component's state and Redux is tricky, so I had to do some weird voodoo magic to force it to work. Here's an explanation of how it works:

https://github.com/PatheticMustan/ScoutingApp2020/blob/3ee233bcfbc3a94e3b4ce8cad2d43354a2c43961/Components/Utility/CustomTextBox.js#L28-L42

What we need is to put this monstrosity of code in all of our input components, such as `BoolButton`, `NumButton`, `RadioButton`, and more.

It'd be best to make this a simple solution as possible. Worst case scenario, we copy paste this atrocity in all of our components. This would make it way too complicated for a new developer to make a new component...

**Comment by KryptoCrash** [comment]
why dont we just make a component to store this function and then all input components can inherit the function

**Comment by PatheticMustan** [comment]
ok, please do that

**Comment by 00100000** [comment]
haha I'm gonna unassign myself because I know my place. Have fun with this d4 guys!

**Comment by PatheticMustan** [comment]
I'll try working on this today

**Comment by PatheticMustan** [comment]
### Boiling down components to... their components

**Refactoring Redux, and rethinking our input components.**
Unfortunately, because the only one who worked on state, and therefore the only one who even bothered to learn Redux, is insane, some of the early decisions with Redux are now blindingly short sighted.
We are facing huge exponential performance losses, and it has become a great burden to even try setting up an input component. Adding anything new requires an eldritch being, the sacrifice of a newborn, and deep understanding of our current architecture.

We must always look back to our ideals:
	⁃	Must be easy to add to
	⁃	Must be dynamic
	⁃	Should be fast
	⁃	Should be easy to understand
With this in mind, we can move forwards with refactorization in mind.

**Instantiation**
The component is instantiated with a props.id, which is used to update the right KPV. Two props sharing the same id update the same value.
The hope is that once you specify the id, the input should handle all the redux heavy lifting after that.

**Performance concerns with KPV**
KPV is an array with N inputs. Each time an input updates, it updates everything subscribed to KPV, which is greater than or equal to N. Each component loops through all of KPV to find their own value, and update KPV. They loop through N items.
This means with each input update, comes around N**3 checks. Whatever. To be exact, N*Inputs*N, so slightly greater than N cubed.
For inputs below 10, it doesn't matter. But after a while, since performance degrades exponentially, this becomes a searing pain to deal with. Currently we have about 35 something inputs.
We quickly need to restructure how we deal with KPV. Maybe instead of components checking every single time, we can just assign an index...?
Or maybe instead of being an array, KPV can be an object. That would make a lot more sense both syntactically and performance wise.
That way, we can avoid all these .find() calls.
It would also feel much cleaner.

**Updating redux, updating state**
We need to constantly update redux, but also keep component state.
Especially keeping performance in mind, many successive dispatch calls are not good for performance, and stress the store.
Unfortunately, we also want linked components (inputs with the same id) to update each other at the same time, not at a delay.

To summarize:
	⁃	We could send redux events at an interval but;
	⁃	that would mean linked components also update at an interval
In one specific case, we want to link an incrementor and a textbox together.

How can we solve this problem?
????

And another case, the textbox, which updates too fast for Redux to catch up, causing it to occasionally infinitely rubberband.
???????

Redux should only update when the components update, or from a reset or loadmatch.

Maybe instead of Redux holding the values of the components, it can hold references to the components??? It would allow components of the same id to update instantly at the same time, but I don't know if it's possible in Javascript.
I highly doubt it's even possible, but I should search it up later.

Search up "React Native passing hooks"

>Search up "React Native passing hooks"
So it's not possible ;(

Maybe the Redux dispatch can also send the props.id, and Redux can handle the updating shit... isn't that already what happens...? I think so...

**Comment by PatheticMustan** [comment]
just for textboxes, I was thinking about updating the text with component state, then updating redux when the user finishes typing...

or... instead of components updating at an interval they could keep state with component state, update after a certain amount of time with no changes, and update component state when redux updates....

**Comment by PatheticMustan** [comment]
just to be clear, I'm switching store.data.keyPairValues from a 2d Array [[key, value]] to an Object {key: value}
